<a href="https://colab.research.google.com/github/RajulapatiKiransri/DecisionTreeClassifier/blob/decision_tree_classifier/Decision_Tree_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
x = data.data
y = data.target
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=30,test_size=0.45)
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
print("Train data accuracy:",accuracy_score(y_true = y_train,y_pred = clf.predict(x_train)))
print("Test data accuracy:",accuracy_score(y_true = y_test,y_pred = y_pred))


Train data accuracy: 1.0
Test data accuracy: 0.9558823529411765


In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[19  0  0]
 [ 0 24  2]
 [ 0  1 22]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.96      0.92      0.94        26
           2       0.92      0.96      0.94        23

    accuracy                           0.96        68
   macro avg       0.96      0.96      0.96        68
weighted avg       0.96      0.96      0.96        68

